"""company join codes

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 03:17:46.145146

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("companies", sa.Column("join_code", sa.String(length=12), nullable=False))
    op.create_unique_constraint("uq_companies_join_code", "companies", ["join_code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("uq_companies_join_code", "companies", type_="unique")
    op.drop_column("companies", "join_code")
    # ### end Alembic commands ###
